# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Brewery.create(name: 'Wiseacre', city: 'Memphis', state: 'TN', postal_code: '38139')
Brewery.create(name: 'Yazoo', city: 'Nashville', state: 'TN', postal_code: '32891')
Brewery.create(name: 'Avondale Brewing Co', city: 'Birmingham', state: 'AL')
Brewery.create(name: 'Mother’s Brewing Co', city: 'Springfield', state: 'MO')
Brewery.create(name: 'Springfield Brewing Co', city: 'Springfield', state: 'MO')
Brewery.create(name: 'Stone’s Throw Brewing', city: 'Little Rock', state: 'AR')
Brewery.create(name: 'Vino’s Brewpub', city: 'Little Rock', state: 'AR')
Brewery.create(name: 'Jackalope Brewing Co', city: 'Nashville', state: 'TN')
Brewery.create(name: 'Perennial Artisan Ales', city: 'St Louis', state: 'MO')
Brewery.create(name: 'Schlafly Tap Room', city: 'St Louis', state: 'MO')
Brewery.create(name: 'Urban Chestnut Brewery', city: 'St Louis', state: 'MO')
Brewery.create(name: 'Base Camp Brewing Co', city: 'Portland', state: 'OR')
Brewery.create(name: 'Hair of the Dog Brewing Co', city: 'Portland', state: 'OR')
Brewery.create(name: 'Dirty Hands Brewing Co', city: 'Vancouver', state: 'WA')
Brewery.create(name: 'Loowit Brewing Co', city: 'Vancouver', state: 'WA')
Brewery.create(name: 'Rogue Ales Public House & Distillery', city: 'Portland', state: 'OR')
Brewery.create(name: 'Cascade Brewing', city: 'Portland', state: 'OR')
Brewery.create(name: 'Buckman Botanical Brewery', city: 'Portland', state: 'OR')
Brewery.create(name: 'Hopworks Urban Brewery', city: 'Portland', state: 'OR')
Brewery.create(name: 'Laurelwood Brewing Co', city: 'Portland', state: 'OR')
Brewery.create(name: 'High Cotton Brewing', city: 'Memphis', state: 'TN')
Brewery.create(name: 'Comrade Brewing Co', city: 'Denver', state: 'CO')
Brewery.create(name: 'Strange Craft Beer Co', city: 'Denver', state: 'CO')
Brewery.create(name: 'Wit’s End Brewing Co', city: 'Denver', state: 'CO')
Brewery.create(name: 'Wyncoop Brewing Co', city: 'Denver', state: 'CO')
Brewery.create(name: 'Wicked Weed Brewing', city: 'Asheville', state: 'NC')
Brewery.create(name: 'Green Man Brewery', city: 'Asheville', state: 'NC')
Brewery.create(name: 'Burial Beer Co', city: 'Asheville', state: 'NC')
Brewery.create(name: 'Wedge Brewery', city: 'Asheville', state: 'NC')
Brewery.create(name: 'Hi Wire Brewery', city: 'Asheville', state: 'NC')
Brewery.create(name: 'Asheville Brewery', city: 'Asheville', state: 'NC')
Brewery.create(name: 'NoDa Brewing Co', city: 'Charlotte', state: 'NC')
Brewery.create(name: 'Birdsong Brewing Co', city: 'Charlotte', state: 'NC')
Brewery.create(name: 'Half Acre Beer Co', city: 'Chicago', state: 'IL')
Brewery.create(name: 'Black Abbey Brewing Co', city: 'Nashville', state: 'TN')
Brewery.create(name: 'Turtle Anarchy Brewing Co', city: 'Franklin', state: 'TN')
Brewery.create(name: 'Ferguson Brewing Co', city: 'Ferguson', state: 'MO')
Brewery.create(name: 'Exit 6 Brewery', city: 'St Charles', state: 'MO')
Brewery.create(name: '4 Hands Brewing Co', city: 'St Louis', state: 'MO')
Brewery.create(name: 'Civil Life Brewing Co', city: 'St Louis', state: 'MO')
Brewery.create(name: 'Czann’s Brewing Co', city: 'Nashville', state: 'TN')
Brewery.create(name: 'Cobra Brewing Co', city: 'Lewisville', state: 'TX')
Brewery.create(name: 'Four Corners Brewing Co', city: 'Dallas', state: 'TX')
Brewery.create(name: 'Memphis Made Brewing Co', city: 'Memphis', state: 'TN')
Brewery.create(name: 'Minglewood Brewery', city: 'Cape Girardeau', state: 'MO')
Brewery.create(name: 'Chattanooga Brewing Co', city: 'Chattanooga', state: 'TN')
Brewery.create(name: 'Jailhouse Brewing Co', city: 'Hampton', state: 'GA')
Brewery.create(name: 'Wrecking Bar Brewpub', city: 'Atlanta', state: 'GA')
Brewery.create(name: 'Good People Brewing Co', city: 'Birmingham', state: 'AL')
Brewery.create(name: 'Cool Springs Brewery', city: 'Franklin', state: 'TN')
Brewery.create(name: 'Yazoo Brewing Co', city: 'Nashville', state: 'TN')
Brewery.create(name: 'Honky Tonk Brewing Co', city: 'Nashville', state: 'TN')
Brewery.create(name: 'Fat Bottom Brewing Co', city: 'Nashville', state: 'TN')
Brewery.create(name: 'Mayday Brewery', city: 'Murfreesboro', state: 'TN')
Brewery.create(name: 'Threes Brewing', city: 'Brooklyn', state: 'NY')
Brewery.create(name: 'Other Half Brewing Co', city: 'Brooklyn', state: 'NY')
Brewery.create(name: 'Transmitter Brewing', city: 'Long Island City', state: 'NY')
Brewery.create(name: 'Singlecut Brewerey', city: 'Queens', state: 'NY')
Brewery.create(name: 'Rockaway Brewing Co', city: 'Long Island City', state: 'NY')
Brewery.create(name: 'Big Alice Brewing', city: 'Long Island City', state: 'NY')
Brewery.create(name: 'Cahaba Brewing Co', city: 'Birmingham', state: 'AL')
Brewery.create(name: 'Trim Tab Brewing Co', city: 'Birmingham', state: 'AL')
Brewery.create(name: 'Yalobusha Brewery', city: 'Water Valley', state: 'MS')
Brewery.create(name: 'Courtyard Brewing Co', city: 'New Orleans', state: 'LA')
Brewery.create(name: 'Nola Brewing Co', city: 'New Orleans', state: 'LA')
Brewery.create(name: '5 Seasons Brewing', city: 'Atlanta', state: 'GA')
Brewery.create(name: 'Second Self Beer Co', city: 'Atlanta', state: 'GA')
Brewery.create(name: 'Sweet Water Brewing Co', city: 'Atlanta', state: 'GA')
Brewery.create(name: 'Fullsteam Brewing Co', city: 'Durham', state: 'NC')
Brewery.create(name: 'Bull City Burger & Brewery', city: 'Durham', state: 'NC')
Brewery.create(name: 'Ponysaurus Brewing Co', city: 'Durham', state: 'NC')
Brewery.create(name: 'Steel String Craft Brewery', city: 'Chapel Hill', state: 'NC')
Brewery.create(name: 'Lonerider Brewing Co', city: 'Raleigh', state: 'NC')
Brewery.create(name: 'Fortnight Brewing Co', city: 'Cary', state: 'NC')
Brewery.create(name: 'Brüeprint Brewing Co', city: 'Apex', state: 'NC')
Brewery.create(name: 'Yester Years Brewing Co', city: 'Chapel Hill', state: 'NC')
Brewery.create(name: 'LauderAle Brewing Co', city: 'Ft. Lauderdale ', state: 'FL')
Brewery.create(name: 'Gulf Coast Brewery ', city: 'Pensacola', state: 'FL')
Brewery.create(name: 'Pensacola Bay Brewery', city: 'Pensacola', state: 'FL')
Brewery.create(name: 'Second Line Brewing Co', city: 'New Orleans', state: 'LA')
